/**
 * **Code explainability — can I change this without breaking something?**
 *
 * **Who.** An engineer three days into a codebase they did not write, holding a
 * ticket that says "make `type` required on the node record". Or the same
 * engineer six months later, asked in review why a change is safe.
 *
 * **The question.** *Where does a node actually become a pixel — and if I change
 * its shape, what is downstream of me?*
 *
 * A file tree cannot answer that. Neither can grep: the answer is a **path**
 * through 42 symbols across 5 packages, and the useful thing about it is which
 * hops exist, not which files contain a word.
 *
 * ### The data
 *
 * `canvasDataflow` — this monorepo's own type / instance graph. Every node is a
 * real symbol with its source location on `data.file`; every edge a traced
 * relationship (`creates` · `implements` · `compiles-to` · `instantiates` · …).
 * It is **not** generated by a static analyser: it was hand-traced, which is why
 * each node carries a `purpose` line that no AST walk would produce.
 *
 * ### How the visualiser helps — step by step
 *
 * 1. **Open the whole stack.** 42 cards, coloured by side of the system —
 *    app / data / engine / render. The shape of the pipeline is one glance.
 * 2. **Read a symbol without leaving the graph.** Each card carries what kind of
 *    construct it is, who owns it, and one line on why it exists. This is the
 *    step a file tree cannot do at all.
 * 3. **Hover to isolate a neighbourhood.** Everything off the 1-hop path dims —
 *    at 42 nodes that is the only practical way to follow one thread.
 * 4. **Find the seam.** `nodeSpec` and `edgeSpec` are the *only* two crossings
 *    from graph vocabulary to canvas vocabulary. Everything above them speaks
 *    `GraphNode`; everything below speaks `BaseShapeSpec`. That is the answer to
 *    the ticket: a record change stops there.
 * 5. **Switch to dots** when the question turns from *"what is this"* to
 *    *"what is the shape"* — the same graph, the compact reading.
 * 6. **Open Settings** to re-cut the picture without editing the story: the ELK
 *    direction and spacing, the hover degree, every mounted behaviour. The panel
 *    lists exactly what this canvas registers — which is why the app bundle is
 *    off (`bundle={false}`) and the children below are the whole composition.
 *
 * ### What it makes obvious
 *
 * Three things that are true of the code and invisible in the source tree:
 *
 * - **`@invana/canvas` has no `record` node.** A shape exists only as a *spec*
 *   handed in and an *instance* the renderer holds — all persistence is
 *   graph-side. So "where is the canvas equivalent of `GraphNode`" has the
 *   answer *nowhere*, and that is by design.
 * - **`GraphStore → DataSource` is `implements`, not `extends`.** The kernel
 *   never learns what a graph is; it knows three methods.
 * - **Edges fan into four sub-choices** (anchor · router · pathStyle · marker)
 *   where nodes make one. That asymmetry explains why `NodeShapeOptions` is a
 *   discriminated union and `EdgeShapeOptions` is a flat interface.
 */

import { useCallback, useMemo, useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import {
  BackgroundLayer,
  BrushSelectBehaviour,
  CanvasThemeSync,
  ClickSelectBehaviour,
  CollapseExpandBehaviour,
  ColorByBehaviour,
  DragNodeBehaviour,
  DragPanBehaviour,
  ElkLayout,
  GraphLayer,
  HoverActivateBehaviour,
  LassoSelectBehaviour,
  TextResolutionLODBehaviour,
  ThemeBehaviour,
  WheelZoomBehaviour
} from '@invana/canvas-react';
import {
  CanvasMessageBar,
  CanvasSettingsEditorPanel,
  GraphCanvasApp,
  GraphControlsToolbar,
  GraphStatusBar,
  ToolbarItems,
  useSidePanels
} from '@invana/canvas-ui';
import { canvasDataflow } from '@invana/graph-datasets';
import type { CanvasConfig } from '@invana/canvas';
import type {
  GraphCanvas,
  NodeStructureRegistry,
  NodeStylingRegistry,
  NodeTypeRegistry
} from '@invana/graph';
import { Moon, Settings, Sun } from 'lucide-react';


// ─── Presentation ────────────────────────────────────────────────────────────
//
// The dataset is data only — it describes what the symbols are, not how to draw
// them. Everything below is this story's answer to "how should they look".

/** Card box. ELK is handed the same numbers the card draws at. */
const CARD = { width: 264, height: 132 } as const;

/**
 * One structure for all 42 symbols — the cards differ by *styling*, not shape.
 *
 * The row order is the reading order: what kind of construct it is and who owns
 * it, then the name, then the one line on why it exists. `purpose` is the
 * payload; a dot with a label could never carry it.
 */
const structures: NodeStructureRegistry = {
  symbolCard: {
    name: 'symbolCard',
    kind: 'card',
    width: CARD.width,
    height: CARD.height,
    rows: [
      { slots: [{ slot: 'symbol', kind: 'tag' }, { slot: 'package', kind: 'text' }] },
      { divider: true },
      { slots: [{ slot: 'name', kind: 'text' }] },
      { slots: [{ slot: 'purpose', kind: 'text' }] },
    ]
  }
};

/**
 * Four stylings, grouped by **side of the stack** rather than by the twelve
 * `type` layers — the accent works as a legend, and twelve accents would be
 * noise. Roles carry the theme; only `accent` is a literal, because the palette
 * exposes one accent role and this card wants four.
 *
 * Written out rather than built by a helper. Four near-identical literals are
 * more text than one factory called four times, but a template registry is
 * **data** — it has to survive being saved, reloaded and edited in the settings
 * panel, and a reader comparing two accents should see the difference on the
 * page rather than reconstruct it from a call. This is also what Storybook's
 * "Show code" tab shows.
 *
 * The hairline border is doing real work, not decoration: a card's `cardBg` sits
 * one step off the frame it's drawn on, and at a zoom where the text stops being
 * legible that step alone isn't enough to read the card as an object. The border
 * is what keeps 42 cards countable. It goes through `strokeRole` rather than a
 * literal so it still tracks the palette in light mode.
 */
const stylings: NodeStylingRegistry = {
  // React + facade — where a consumer starts
  appCard: {
    name: 'appCard',
    bgRole: 'cardBg',
    strokeRole: 'stroke',
    strokeWidth: 1,
    accent: 0x8b5cf6,
    slots: {
      symbol: { color: 0x8b5cf6, fontSize: 10, fontWeight: 700, uppercase: true },
      package: { colorRole: 'muted', fontSize: 10 },
      name: { colorRole: 'heading', fontSize: 15, fontWeight: 700 },
      purpose: { colorRole: 'foreground', fontSize: 11 },
      divider: { colorRole: 'divider' }
    }
  },
  // records, styles, stores — the data lanes
  dataCard: {
    name: 'dataCard',
    bgRole: 'cardBg',
    strokeRole: 'stroke',
    strokeWidth: 1,
    accent: 0x10b981,
    slots: {
      symbol: { color: 0x10b981, fontSize: 10, fontWeight: 700, uppercase: true },
      package: { colorRole: 'muted', fontSize: 10 },
      name: { colorRole: 'heading', fontSize: 15, fontWeight: 700 },
      purpose: { colorRole: 'foreground', fontSize: 11 },
      divider: { colorRole: 'divider' }
    }
  },
  // engine, layer, behaviour, interface
  engineCard: {
    name: 'engineCard',
    bgRole: 'cardBg',
    strokeRole: 'stroke',
    strokeWidth: 1,
    accent: 0xf59e0b,
    slots: {
      symbol: { color: 0xf59e0b, fontSize: 10, fontWeight: 700, uppercase: true },
      package: { colorRole: 'muted', fontSize: 10 },
      name: { colorRole: 'heading', fontSize: 15, fontWeight: 700 },
      purpose: { colorRole: 'foreground', fontSize: 11 },
      divider: { colorRole: 'divider' }
    }
  },
  // spec, instance, renderer — canvas-side
  renderCard: {
    name: 'renderCard',
    bgRole: 'cardBg',
    strokeRole: 'stroke',
    strokeWidth: 1,
    accent: 0xf43f5e,
    slots: {
      symbol: { color: 0xf43f5e, fontSize: 10, fontWeight: 700, uppercase: true },
      package: { colorRole: 'muted', fontSize: 10 },
      name: { colorRole: 'heading', fontSize: 15, fontWeight: 700 },
      purpose: { colorRole: 'foreground', fontSize: 11 },
      divider: { colorRole: 'divider' }
    }
  },
};

/**
 * The package frame — a type like any other, declared the same way.
 *
 * `group` is what makes a node a container (`GraphLayer.isGroupNode`), and it
 * sits on the **styling** template because that is what it is: the dataset
 * states the hierarchy (`parentId` → package), and whether that hierarchy
 * *renders* as a frame is presentation. Declaring it per type is what keeps it
 * out of a `node.style` resolver, so this whole config stays JSON.
 *
 * `autoFit` is REQUIRED, not decoration: it defaults to `false`, and without it
 * the frame ignores its children and draws at its declared size.
 *
 * The declared `rect` does double duty and both halves matter: expanded it is
 * the *floor* auto-fit raises to the children bbox + padding, and **collapsed
 * it is the size the frame keeps** — auto-fit is skipped and a rect has no
 * `collapsedOf` minimal form. Declaring `0 × 0` frames correctly but closes to
 * a 0×0 rect: an invisible node you can't double-click to re-open. So:
 * card-width, one header tall. Without any shape at all it would fall to the
 * engine default (`circle radius:10`) and auto-fit would grow that into a vast
 * enclosing circle.
 */
const FRAME_STRUCTURES: NodeStructureRegistry = {
  packageFrame: {
    name: 'packageFrame',
    kind: 'simple',
    shape: { kind: 'rect', width: CARD.width, height: 52, cornerRadius: 14 },
    slots: { label: true }
  }
};

/**
 * **A group node is just a node, so it takes ordinary node styling.** There is
 * no group-specific fill channel and none is needed.
 *
 * Three surfaces, and the frame has to sit *between* the backdrop and the card
 * so the card still reads as the raised thing. The cards' colours go through
 * roles, so they follow the theme — but a raw colour is a plain number with no
 * role channel, so a literal picked for dark mode would be wrong the moment the
 * header's theme toggle flips to light.
 *
 * The way out is a **neutral tinted with alpha rather than a chosen colour**:
 * mid-slate at 14% composites *against whatever backdrop is behind it*. Over the
 * dark backdrop it lands near 0x1b2436 — a step up from the background, a step
 * below `cardBg`. Over the light one it lands near 0xe9ecf0 — a step *down*,
 * with the near-white card still the raised surface. The ordering that makes a
 * card read as raised survives either way, from one pair of values.
 *
 * `fillAlpha` tints the **fill only**. The whole-shape `bgAlpha` would multiply
 * the border too — a 0.75 border under a 0.14 shape opacity paints at 0.1,
 * which is why these frames once looked borderless.
 */
const FRAME_STYLINGS: NodeStylingRegistry = {
  packageFrame: {
    name: 'packageFrame',
    group: { autoFit: true, padding: 28, headerHeight: 26 },
    fill: 0x64748b,
    fillAlpha: 0.14,
    stroke: 0x94a3b8,
    strokeAlpha: 0.75,
    strokeWidth: 1.5
  }
};

/**
 * Every node type, bound to a structure + styling + its slot→data paths.
 *
 * `bindings` values are **dotted paths into the record**, read verbatim — so
 * `label: 'id'` on the frame reads `node.id`, and `name: 'data.name'` reads the
 * payload. That is how a label's *content* stays declarative: no accessor, no
 * `labelText` resolver.
 *
 * Twelve entries repeating one structure is deliberate. A `bind(styling)` helper
 * was shorter, but this registry is data the settings panel loads, edits and
 * saves; a factory call is not something a saved config can contain, and it
 * hides which types share a styling behind a function name. Grouped by side of
 * the stack, the repetition *is* the legend.
 */
const nodeTypes: NodeTypeRegistry = {
  // The frame is a type binding like any other — this entry is what replaced
  // seven `node.style` resolvers.
  package: { structure: 'packageFrame', styling: 'packageFrame', bindings: { label: 'id' } },

  react: {
    structure: 'symbolCard',
    styling: 'appCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  facade: {
    structure: 'symbolCard',
    styling: 'appCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  engine: {
    structure: 'symbolCard',
    styling: 'engineCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  layer: {
    structure: 'symbolCard',
    styling: 'engineCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  behaviour: {
    structure: 'symbolCard',
    styling: 'engineCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  interface: {
    structure: 'symbolCard',
    styling: 'engineCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  store: {
    structure: 'symbolCard',
    styling: 'dataCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  record: {
    structure: 'symbolCard',
    styling: 'dataCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  style: {
    structure: 'symbolCard',
    styling: 'dataCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  spec: {
    structure: 'symbolCard',
    styling: 'renderCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  instance: {
    structure: 'symbolCard',
    styling: 'renderCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
  renderer: {
    structure: 'symbolCard',
    styling: 'renderCard',
    bindings: { symbol: 'data.symbol', package: 'data.package', name: 'data.name', purpose: 'data.purpose' }
  },
};

/**
 * Cards — the default. `purpose` is the payload and a labelled dot cannot carry
 * a sentence.
 *
 * Colour-by-type is **off**: the card styling owns the fill, and a `bgFill`
 * resolver would fight it. Type is still doing the work — it *selects* which
 * styling a node gets.
 *
 * `fitOnLoad` is off deliberately: it measures before a one-shot layout resolves
 * and lands at ~170% (`docs/autofit-bounds-rfc.md`).
 */
const CARD_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    // The app bundle is off (`bundle={false}` below — it would register a
    // d3-force layout this story has no use for), so every setting the bundle
    // used to supply is spelled out here, keyed by the id each JSX child
    // registers under.
    background: { type: 'pattern', patternType: 'grid', alpha: 0.5 },
    graph: {
      // The frame's structure + styling join the card ones — one registry each,
      // no per-node branching anywhere.
      nodeStructureTemplates: { ...structures, ...FRAME_STRUCTURES },
      nodeStylingTemplates: { ...stylings, ...FRAME_STYLINGS },
      nodeTypes,
      edge: {
        style: {
          strokeColor: 0x94a3b8,
          // Legible at the zoom this graph actually gets read at. 42 cards fit
          // at ~26%, where a 1.2px line at 40% alpha is a sub-pixel smudge —
          // the edges were marginal even over open backdrop, before the group
          // frames were painting over them at all.
          strokeWidth: 1.6,
          strokeAlpha: 0.7,
          arrowTargetShape: 'triangle',
          arrowTargetSize: 5
        }
      }
    }
  },
  layouts: {
    // LEFT-TO-RIGHT: the stack reads app → data → engine → render, which is a
    // sentence, and sentences read across.
    elk: {
      algorithm: 'layered',
      direction: 'RIGHT',
      // These apply at both levels — between the package frames *and* between
      // the cards inside them — so they're a compromise, not a per-level tune.
      //
      // They were briefly much larger (96 / 190) to force the frames apart, back
      // when a container's members were pinned at ELK's default 20px spacing no
      // matter what was configured (fixed in `ElkLayout`'s `nestedLayoutOptions`
      // — containers declare their own `layoutOptions`, so they used to opt out
      // of every spacing key set on the root). With the inner spacing honoured,
      // those numbers inflated the graph to ~18% zoom-to-fit; these are the
      // values that read well now that one setting actually reaches both levels.
      nodeSpacing: 48,
      layerSpacing: 140,
      edgeNodeSpacing: 24,
      edgeSpacing: 14,
      padding: 40,
      // Fallback only — used when a node's shape can't be measured, which for
      // this look means a card, so these are the card's own numbers.
      defaultNodeSize: { width: CARD.width, height: CARD.height }
    }
  },
  behaviours: {
    // Colour-by-type is off: the card styling owns the fill, and a `bgFill`
    // resolver would fight it.
    color: { enabled: false },
    // A package frame is scenery, not content. It is picked like any other
    // shape (`plane: 'backdrop'` moves only where it *paints*), and with
    // `autoFit` most of its area is uncovered — so grazing its padding used to
    // hover the frame, and since a frame carries no edges for `degree` to
    // expand into, `inactiveState` dimmed all 42 cards at once.
    //
    // `excludeNodeTypes` takes the frames out of the focal hover by data, not
    // by callback: it is plain JSON, so it survives a saved config and shows up
    // in the Settings panel. Only the *focal* element is vetoed — a package
    // reached as a neighbour would still highlight — and the frame stays
    // pickable, which is what keeps `drag-node` and `collapse-expand` working
    // on it.
    hover: {
      enabled: true,
      state: 'highlighted',
      // inactiveState: 'dimmed',
      degree: 1,
      direction: 'both',
      excludeNodeTypes: ['package']
    },
    pan: { enabled: true },
    wheel: { enabled: true },
    'drag-node': { enabled: true },
    // Same veto for clicks. A click on an excluded node is a no-op rather than
    // a clear, so aiming at a gap never costs you the selection.
    'click-select': { enabled: true, multiple: true, excludeNodeTypes: ['package'] },
    // Registered disarmed — the toolbar's select-mode picker arms one at a time.
    'brush-select': { enabled: false },
    'lasso-select': { enabled: false },
    // Re-rasterise glyphs as the camera zooms in. Pixi rasterises each text to
    // a glyph texture once at the renderer's DPR, so a card read at 3× is that
    // same texture upsampled 3× — legible but soft, which is the wrong failure
    // mode for a story whose whole payload is a sentence per card. This reaches
    // the card text, not just the frame titles: composite `label` parts aren't
    // decorations, so `setLabelsResolution` pushes into them directly
    // (`PrimitivesRenderer.ts:1544`).
    //
    // Tiers are left at the default ladder — four widely-spaced bands whose
    // multipliers are derived in the source (`DEFAULT_LEVELS`) to hold sampling
    // at ≥ ~1 glyph-pixel per screen pixel. Each boundary crossed costs one GPU
    // re-raster of every label, which is why the bands are wide; at 47 labels
    // here it is imperceptible either way.
    'label-resolution': { enabled: true },
    // A package frame's +/- toggle and double-click-to-collapse.
    'collapse-expand': { enabled: true },
    // The sole theme publisher; `<CanvasThemeSync>` pins its mode + family to
    // the host `<ThemeProvider>`, so the header toggle repaints the canvas.
    theme: { enabled: true, mode: 'system', active: 'default', accent: 'css-var' }
  }
};

/**
 * Dots — the compact reading. Same graph, different question: cards answer
 * *"what is this symbol"*, dots answer *"what is the shape of the pipeline"*.
 * Colour-by-type is on here because nothing competes for the fill.
 */
const DOT_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    background: { type: 'pattern', patternType: 'grid', alpha: 0.5 },
    graph: {
      // The dot look shares the frame templates; only the frame's own geometry
      // differs, so it gets its own structure and reuses the styling verbatim.
      nodeStructureTemplates: {
        packageFrame: {
          name: 'packageFrame',
          kind: 'simple',
          shape: { kind: 'rect', width: 168, height: 40, cornerRadius: 12 },
          slots: { label: true }
        }
      },
      nodeStylingTemplates: {
        packageFrame: { ...FRAME_STYLINGS.packageFrame!, group: { autoFit: true, padding: 20, headerHeight: 22 } }
      },
      nodeTypes: { package: { structure: 'packageFrame', styling: 'packageFrame', bindings: { label: 'id' } } },
      node: {
        style: {
          // Every non-package node is a dot. The frame overrides this through
          // its own type binding, which wins over the layer template.
          shape: { kind: 'circle' as const, radius: 8 },
          bgStrokeColor: 0x94a3b8,
          bgStrokeAlpha: 0.9,
          bgStrokeWidth: 1.5,
          labelFontSize: 10,
          labelPlacement: 'bottom' as const,
          labelOffsetY: 4
        }
      },
      edge: {
        style: { strokeColor: 0x94a3b8, strokeWidth: 1.6, strokeAlpha: 0.7, arrowTargetShape: 'none' }
      }
    }
  },
  layouts: {
    elk: {
      algorithm: 'layered',
      direction: 'RIGHT',
      nodeSpacing: 18,
      layerSpacing: 90,
      padding: 30,
      // Fallback only — see CARD_CONFIG. A dot is 8px of radius, so 20 square
      // is the same "about one node" box the callback used to hand over.
      defaultNodeSize: { width: 20, height: 20 }
    }
  },
  // Same hand-rolled bundle as CARD_CONFIG (see the note there) — except
  // colour-by-type, which is on here because nothing competes for the fill.
  behaviours: {
    color: { enabled: true },
    // Same frame veto as CARD_CONFIG — see the note there.
    hover: {
      enabled: true,
      state: 'highlighted',
      inactiveState: 'dimmed',
      degree: 1,
      direction: 'both',
      excludeNodeTypes: ['package']
    },
    pan: { enabled: true },
    wheel: { enabled: true },
    'drag-node': { enabled: true },
    'click-select': { enabled: true, multiple: true, excludeNodeTypes: ['package'] },
    'brush-select': { enabled: false },
    'lasso-select': { enabled: false },
    'collapse-expand': { enabled: true },
    // Same as CARD_CONFIG — see the note there. The dot look's labels are
    // ordinary label decorations rather than composite parts, and at 10px they
    // are the first thing to go soft on a zoom-in.
    'label-resolution': { enabled: true },
    theme: { enabled: true, mode: 'system', active: 'default', accent: 'css-var' }
  }
};

const meta: Meta = { title: 'usecases/by-casestudies/code-explainability/CodeExplainability' };
export default meta;
type Story = StoryObj;

export const CodeExplainabilityStory: Story = {
  name: 'CodeExplainability',
  render: function CodeExplainabilityRender() {
    /** Cards carry the prose; dots carry the topology. Same graph either way. */
    const [look, setLook] = useState<'cards' | 'dots'>('cards');

    // Settings docks `<CanvasSettingsEditorPanel>` into the right region — the
    // ELK direction / spacing and every mounted behaviour, editable live. That
    // panel is why the header carries no layout controls of its own.
    const dock = useSidePanels(
      [
        {
          id: 'settings',
          icon: Settings,
          label: 'Settings',
          render: (c) => (
            <CanvasSettingsEditorPanel canvas={c} className="border-0 bg-transparent shadow-none" />
          )
        },
      ],
      { section: { defaultSize: '380px', maxSize: '520px' } },
    );

    // Memoised so a toolbar change never hands GraphCanvasApp a new `data`
    // identity and reloads the engine.
    const data = useMemo(() => canvasDataflow, []);
    const config = useMemo(
      () => (look === 'cards' ? CARD_CONFIG : DOT_CONFIG),
      [look],
    );

    const onReady = useCallback((c: GraphCanvas | null) => {
      if (!c) return;
      c.showMessage('Hover a symbol to isolate its 1-hop neighbourhood');
      // No fit here. `config.fitOnLoad` is off (it measures before a one-shot
      // layout resolves — `docs/autofit-bounds-rfc.md`), and a hand-rolled
      // `setTimeout(fitView, 400)` is the same bug on a timer: ELK's solve time
      // moves with the look, so the timer fires mid-solve and frames a near-empty
      // bbox — ~770% on the dot look. `<ElkLayout fitPadding={60}>` fits off the
      // layout's own `end` event instead, which is the only signal that can't be
      // early.
    }, []);

    return (
      <GraphCanvasApp
        data={data}
        config={config}
        onReady={onReady}
        // `bundle={false}` — the batteries-included bundle registers a
        // d3-force layout, and this graph is laid out by ELK alone. Turning it
        // off makes the children below the *whole* canvas, which is also what
        // keeps the settings panel honest: it lists exactly what's mounted, so
        // a layout nothing points at never shows up as an editable surface.
        bundle={false}
        // The switch below is not a config *tweak*: cards and dots differ in
        // which node templates exist at all. `config` is applied with
        // `canvas.update()`, which deep-merges (`Canvas.ts:761`) — and
        // `GraphLayer.setOptions` merges `nodeTypes` key-by-key
        // (`GraphLayer.ts:874`), so a merge can never *remove* the card
        // bindings. Without a remount the graph stays cards forever (the type
        // binding is applied above the layer template, `GraphLayer.ts:967`).
        // `instanceKey` exists for exactly this: re-init and apply the new
        // config from scratch.
        instanceKey={look}
        header={{
          title: 'Code explainability — where does a node become a pixel?',
          // No layout picker: its default factory constructs a `D3ForceLayout`
          // (`GraphControlsToolbar.tsx:56`), which would put d3-force back in
          // through the front door. ELK's own options live in Settings.
          center: <GraphControlsToolbar sections={{ layout: false }} />,
          right: (ctx) => (
            <ToolbarItems
              orientation="horizontal"
              items={[
                {
                  type: 'select',
                  key: 'look',
                  label: 'Look',
                  value: look,
                  options: { cards: 'Cards — what is this symbol', dots: 'Dots — what is the shape' },
                  onChange: (v) => setLook(v as 'cards' | 'dots')
                },
                ...dock.items,
                {
                  type: 'toggle',
                  key: 'theme',
                  icon: Sun,
                  activeIcon: Moon,
                  label: 'Switch to dark theme',
                  activeLabel: 'Switch to light theme',
                  active: ctx.themeKind === 'dark',
                  onToggle: ctx.toggleTheme
                },
              ]}
            />
          )
        }}
        footer={{ left: <GraphStatusBar />, right: <CanvasMessageBar /> }}
        right={dock.region}
      >
        {/* With the bundle off, these children *are* the canvas — the same set
            `GraphCanvasApp` would have mounted, minus the force layout, plus
            ELK and collapse/expand. Every option comes from `config`, keyed by
            the id each one registers under. */}
        <BackgroundLayer id="background" />
        <GraphLayer id="graph" data={data} />
        <ColorByBehaviour id="color" targetLayerId="graph" />
        {/* The sole theme publisher + the sync that drives its mode/family off
            the host `<ThemeProvider>` — that pair is what makes the header's
            sun/moon toggle repaint the canvas and not just the chrome. */}
        <ThemeBehaviour id="theme" />
        <CanvasThemeSync />
        <DragPanBehaviour id="pan" />
        <WheelZoomBehaviour id="wheel" />
        <DragNodeBehaviour id="drag-node" targetLayerId="graph" />
        <HoverActivateBehaviour id="hover" targetLayerId="graph" />
        <ClickSelectBehaviour id="click-select" targetLayerId="graph" />
        <BrushSelectBehaviour id="brush-select" targetLayerId="graph" />
        <LassoSelectBehaviour id="lasso-select" targetLayerId="graph" />
        {/* The one layout, named by `config.activeLayout`. Every option it takes
            now lives in `config.layouts.elk` — nothing rides the `options` prop,
            so the Settings panel drives all of it (wrapper options are
            init-only; config wins by id).

            No `nodeSize` callback. It used to hand ELK a per-node box, but each
            of its three branches is now answered without a function:

            - **Containers** never needed it. `ElkLayout` discards a container's
              own box and sizes it from its children (or from the declared floor
              via `groupSizeFloor`), so the `{ 0, 0 }` branch was dead code.
            - **Leaves** are measured from their resolved shape — a card
              structure declares `264 × 132`, a dot `radius: 8`.
            - The **fallback**, for a node whose shape can't be measured, is
              `defaultNodeSize` in `config.layouts.elk` — the same numbers, as
              JSON. It is consulted only when resolution fails, so it can't
              override a correct measurement.

            `direction` / spacing / sizing all live in `config.layouts.elk` now,
            which is also what lets the Settings panel drive them. */}
        <ElkLayout id="elk" targetLayerId="graph" fitPadding={60} />
        {/* A package frame's +/- toggle has no listener until this is mounted —
            and neither does double-click, which `doubleClickToToggle` already
            enables by default. Behaviours never auto-enable (root rule 7). */}
        <CollapseExpandBehaviour id="collapse-expand" targetLayerId="graph" enabled />
        {/* Crisp text on zoom-in. The wrapper's default id is `label-lod`; this
            one is named for the id `config.behaviours` keys it under. */}
        <TextResolutionLODBehaviour id="label-resolution" targetLayerId="graph" />
      </GraphCanvasApp>
    );
  }
};
