/**
 * **Code explainability — can I change this without breaking something?**
 *
 * **Who.** An engineer three days into a codebase they did not write, holding a
 * ticket that says "make `type` required on the node record". Or the same
 * engineer six months later, asked in review why a change is safe.
 *
 * **The question.** *Where does a node actually become a pixel — and if I change
 * its shape, what is downstream of me?*
 *
 * A file tree cannot answer that. Neither can grep: the answer is a **path**
 * through 42 symbols across 5 packages, and the useful thing about it is which
 * hops exist, not which files contain a word.
 *
 * ### The data
 *
 * `canvasDataflow` — this monorepo's own type / instance graph. Every node is a
 * real symbol with its source location on `data.file`; every edge a traced
 * relationship (`creates` · `implements` · `compiles-to` · `instantiates` · …).
 * It is **not** generated by a static analyser: it was hand-traced, which is why
 * each node carries a `purpose` line that no AST walk would produce.
 *
 * ### How the visualiser helps — step by step
 *
 * 1. **Open the whole stack.** 42 cards, coloured by side of the system —
 *    app / data / engine / render. The shape of the pipeline is one glance.
 * 2. **Read a symbol without leaving the graph.** Each card carries what kind of
 *    construct it is, who owns it, and one line on why it exists. This is the
 *    step a file tree cannot do at all.
 * 3. **Hover to isolate a neighbourhood.** Everything off the 1-hop path dims —
 *    at 42 nodes that is the only practical way to follow one thread.
 * 4. **Find the seam.** `nodeSpec` and `edgeSpec` are the *only* two crossings
 *    from graph vocabulary to canvas vocabulary. Everything above them speaks
 *    `GraphNode`; everything below speaks `BaseShapeSpec`. That is the answer to
 *    the ticket: a record change stops there.
 * 5. **Switch to dots** when the question turns from *"what is this"* to
 *    *"what is the shape"* — the same graph, the compact reading.
 *
 * ### What it makes obvious
 *
 * Three things that are true of the code and invisible in the source tree:
 *
 * - **`@invana/canvas` has no `record` node.** A shape exists only as a *spec*
 *   handed in and an *instance* the renderer holds — all persistence is
 *   graph-side. So "where is the canvas equivalent of `GraphNode`" has the
 *   answer *nowhere*, and that is by design.
 * - **`GraphStore → DataSource` is `implements`, not `extends`.** The kernel
 *   never learns what a graph is; it knows three methods.
 * - **Edges fan into four sub-choices** (anchor · router · pathStyle · marker)
 *   where nodes make one. That asymmetry explains why `NodeShapeOptions` is a
 *   discriminated union and `EdgeShapeOptions` is a flat interface.
 */

import { useCallback, useMemo, useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CollapseExpandBehaviour, ElkLayout } from '@invana/canvas-react';
import {
  CanvasMessageBar,
  GraphCanvasApp,
  GraphControlsToolbar,
  GraphStatusBar,
  ToolbarItems,
} from '@invana/canvas-ui';
import { canvasDataflow } from '@invana/graph-datasets';
import type { CanvasConfig } from '@invana/canvas';
import type {
  GraphCanvas,
  GraphNode,
  NodeStructureRegistry,
  NodeStylingRegistry,
  NodeTypeRegistry,
} from '@invana/graph';
import type { ElkDirection } from '@invana/graph-layout-elkjs';
import { ThemeProvider } from '@invana/themes';


// ─── Presentation ────────────────────────────────────────────────────────────
//
// The dataset is data only — it describes what the symbols are, not how to draw
// them. Everything below is this story's answer to "how should they look".

/** Card box. ELK is handed the same numbers the card draws at. */
const CARD = { width: 264, height: 132 } as const;

/**
 * One structure for all 42 symbols — the cards differ by *styling*, not shape.
 *
 * The row order is the reading order: what kind of construct it is and who owns
 * it, then the name, then the one line on why it exists. `purpose` is the
 * payload; a dot with a label could never carry it.
 */
const structures: NodeStructureRegistry = {
  symbolCard: {
    name: 'symbolCard',
    kind: 'card',
    width: CARD.width,
    height: CARD.height,
    rows: [
      { slots: [{ slot: 'symbol', kind: 'tag' }, { slot: 'package', kind: 'text' }] },
      { divider: true },
      { slots: [{ slot: 'name', kind: 'text' }] },
      { slots: [{ slot: 'purpose', kind: 'text' }] },
    ],
  },
};

/**
 * One styling shape, four accents.
 *
 * The hairline border is doing real work, not decoration: a card's `cardBg` sits
 * one step off the frame it's drawn on, and at a zoom where the text stops being
 * legible that step alone isn't enough to read the card as an object. The border
 * is what keeps 42 cards countable. It goes through `strokeRole` rather than a
 * literal so it still tracks the palette in light mode.
 */
const card = (accent: number) => ({
  name: 'symbolCard',
  bgRole: 'cardBg' as const,
  strokeRole: 'stroke' as const,
  strokeWidth: 1,
  accent,
  slots: {
    symbol: { color: accent, fontSize: 10, fontWeight: 700, uppercase: true },
    package: { colorRole: 'muted' as const, fontSize: 10 },
    name: { colorRole: 'heading' as const, fontSize: 15, fontWeight: 700 },
    purpose: { colorRole: 'foreground' as const, fontSize: 11 },
    divider: { colorRole: 'divider' as const },
  },
});

/**
 * Four stylings, grouped by **side of the stack** rather than by the twelve
 * `type` layers — the accent works as a legend, and twelve accents would be
 * noise. Roles carry the theme; only `accent` is a literal, because the palette
 * exposes one accent role and this card wants four.
 */
const stylings: NodeStylingRegistry = {
  appCard: card(0x8b5cf6), // React + facade — where a consumer starts
  dataCard: card(0x10b981), // records, styles, stores — the data lanes
  engineCard: card(0xf59e0b), // engine, layer, behaviour, interface
  renderCard: card(0xf43f5e), // spec, instance, renderer — canvas-side
};

/** Bindings are dotted paths into the payload — one path per slot, verbatim. */
const bind = (styling: string) => ({
  structure: 'symbolCard',
  styling,
  bindings: {
    symbol: 'data.symbol',
    package: 'data.package',
    name: 'data.name',
    purpose: 'data.purpose',
  },
});

/** Every stack layer binds to the same structure, styled by its side. */
const nodeTypes: NodeTypeRegistry = {
  react: bind('appCard'),
  facade: bind('appCard'),
  engine: bind('engineCard'),
  layer: bind('engineCard'),
  behaviour: bind('engineCard'),
  interface: bind('engineCard'),
  store: bind('dataCard'),
  record: bind('dataCard'),
  style: bind('dataCard'),
  spec: bind('renderCard'),
  instance: bind('renderCard'),
  renderer: bind('renderCard'),
};

/**
 * Cards — the default. `purpose` is the payload and a labelled dot cannot carry
 * a sentence.
 *
 * Colour-by-type is **off**: the card styling owns the fill, and a `bgFill`
 * resolver would fight it. Type is still doing the work — it *selects* which
 * styling a node gets.
 *
 * `fitOnLoad` is off deliberately: it measures before a one-shot layout resolves
 * and lands at ~170% (`docs/autofit-bounds-rfc.md`).
 */
const CARD_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    graph: {
      nodeStructureTemplates: structures,
      nodeStylingTemplates: stylings,
      nodeTypes,
      node: {
        style: {
          // The dataset states the hierarchy (`parentId` → package); whether it
          // *renders* as a frame is presentation, so the resolver lives here.
          // `style.group` is what makes a node a container — see
          // `GraphLayer.isGroupNode`.
          //
          // `autoFit` is REQUIRED, not decoration: it defaults to `false`, and
          // without it the frame ignores its children and draws at its declared
          // size. A package node carries no `style.shape`, so that size is the
          // engine fallback (`{ kind: 'circle', radius: 10 }`) — a 10px dot that
          // reads as "collapsed" no matter how many symbols it holds.
          group: (node: GraphNode) =>
            node.type === 'package' ? { autoFit: true, padding: 28, headerHeight: 26 } : undefined,
          // A package declares no shape of its own, so without this it falls to
          // the engine default (`circle radius:10`) and autoFit grows that into
          // a vast enclosing circle. A frame around a dozen cards wants a rect.
          //
          // The declared size does double duty and both halves matter: expanded
          // it is the *floor* autoFit raises to the children bbox + padding, and
          // **collapsed it is the size the frame keeps** — autoFit is skipped and
          // a rect has no `collapsedOf` minimal form. Declaring `0 × 0` framed
          // correctly but closed to a 0×0 rect: an invisible node you can't
          // double-click to re-open. So: card-width, one header tall.
          shape: (node: GraphNode) =>
            node.type === 'package'
              ? { kind: 'rect' as const, width: CARD.width, height: 52, cornerRadius: 14 }
              : undefined,
          // **A group node is just a node, so it takes ordinary node styling.**
          // There is no group-specific fill channel and none is needed — `fill`
          // and `stroke` come off the resolved style with no special-casing for
          // frames (`GraphLayer.ts:1526`). Left unset (the default), a package
          // has no fill at all and the frame, its cards and the backdrop read as
          // one flat slab.
          //
          // Three surfaces want three values. The frame sits *between* the
          // backdrop and the card, so the card still reads as the raised thing:
          //   backdrop 0x0f172a  <  frame 0x16203a  <  card `cardBg` 0x1e293b
          // Literals, not roles: a raw `NodeStyle` colour is a number, so unlike
          // the card's `strokeRole` these do not follow the palette — flip the
          // theme to light and the frames need new values.
          // Lighter than the first pass, because `bgAlpha: 0.6` composites the
          // frame against the backdrop: 0x1f2a44 at 60% over 0x0f172a lands near
          // 0x18213a — still clearly a step above the backdrop and a step below
          // the card, which is the ordering that makes the card read as raised.
          // Picking the *final* colour and then adding alpha would have washed
          // the frame back into the background.
          bgFill: (node: GraphNode) => (node.type === 'package' ? 0x1f2a44 : undefined),
          bgAlpha: (node: GraphNode) => (node.type === 'package' ? 0.6 : undefined),
          bgStrokeColor: (node: GraphNode) => (node.type === 'package' ? 0x3f4f6b : undefined),
          bgStrokeWidth: (node: GraphNode) => (node.type === 'package' ? 1 : undefined),
          labelText: (node: GraphNode) => (node.type === 'package' ? node.id : undefined),
        },
      },
      edge: {
        style: {
          strokeColor: 0x94a3b8,
          strokeWidth: 1.2,
          strokeAlpha: 0.4,
          arrowTargetShape: 'triangle',
          arrowTargetSize: 5,
        },
      },
    },
  },
  layouts: {
    // LEFT-TO-RIGHT: the stack reads app → data → engine → render, which is a
    // sentence, and sentences read across.
    elk: {
      algorithm: 'layered',
      direction: 'RIGHT',
      // These apply at both levels — between the package frames *and* between
      // the cards inside them — so they're a compromise, not a per-level tune.
      //
      // They were briefly much larger (96 / 190) to force the frames apart, back
      // when a container's members were pinned at ELK's default 20px spacing no
      // matter what was configured (fixed in `ElkLayout`'s `nestedLayoutOptions`
      // — containers declare their own `layoutOptions`, so they used to opt out
      // of every spacing key set on the root). With the inner spacing honoured,
      // those numbers inflated the graph to ~18% zoom-to-fit; these are the
      // values that read well now that one setting actually reaches both levels.
      nodeSpacing: 48,
      layerSpacing: 140,
      edgeNodeSpacing: 24,
      edgeSpacing: 14,
      padding: 40,
    },
  },
  behaviours: {
    color: { enabled: false },
    hover: { enabled: true, state: 'highlighted', inactiveState: 'dimmed', degree: 1, direction: 'both' },
  },
};

/**
 * Dots — the compact reading. Same graph, different question: cards answer
 * *"what is this symbol"*, dots answer *"what is the shape of the pipeline"*.
 * Colour-by-type is on here because nothing competes for the fill.
 */
const DOT_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    graph: {
      node: {
        style: {
          // `autoFit` + the rect frame for the same reasons as CARD_CONFIG —
          // see the notes there. Here the dot shape is set for every node, so
          // the package has to override it rather than fill a gap.
          group: (node: GraphNode) =>
            node.type === 'package' ? { autoFit: true, padding: 20, headerHeight: 22 } : undefined,
          shape: (node: GraphNode) =>
            node.type === 'package'
              ? { kind: 'rect' as const, width: 168, height: 40, cornerRadius: 12 }
              : { kind: 'circle' as const, radius: 8 },
          // Same three-surface split as CARD_CONFIG. The dot keeps its white
          // rim; the frame takes the muted border, or a 168×40 white-ringed
          // pill would read as the loudest thing on screen.
          bgFill: (node: GraphNode) => (node.type === 'package' ? 0x1f2a44 : undefined),
          bgAlpha: (node: GraphNode) => (node.type === 'package' ? 0.6 : undefined),
          bgStrokeColor: (node: GraphNode) => (node.type === 'package' ? 0x3f4f6b : 0xffffff),
          bgStrokeWidth: (node: GraphNode) => (node.type === 'package' ? 1 : 1.5),
          labelFontSize: 10,
          labelPlacement: 'bottom',
          labelOffsetY: 4,
        },
      },
      edge: {
        style: { strokeColor: 0x94a3b8, strokeWidth: 1.2, strokeAlpha: 0.5, arrowTargetShape: 'none' },
      },
    },
  },
  layouts: {
    elk: { algorithm: 'layered', direction: 'RIGHT', nodeSpacing: 18, layerSpacing: 90, padding: 30 },
  },
  behaviours: {
    color: { enabled: true },
    hover: { enabled: true, state: 'highlighted', inactiveState: 'dimmed', degree: 1, direction: 'both' },
  },
};

const meta: Meta = { title: 'usecases/by-casestudies/code-explainability/CodeExplainability' };
export default meta;
type Story = StoryObj;

export const CodeExplainabilityStory: Story = {
  name: 'CodeExplainability',
  render: function CodeExplainabilityRender() {
    /** Cards carry the prose; dots carry the topology. Same graph either way. */
    const [look, setLook] = useState<'cards' | 'dots'>('cards');
    /** RIGHT reads as a sentence; DOWN is better when the fan-out is wide. */
    const [direction, setDirection] = useState<ElkDirection>('RIGHT');

    // Memoised so a toolbar change never hands GraphCanvasApp a new `data`
    // identity and reloads the engine.
    const data = useMemo(() => canvasDataflow, []);
    const config = useMemo(
      () => (look === 'cards' ? CARD_CONFIG : DOT_CONFIG),
      [look],
    );

    const onReady = useCallback((c: GraphCanvas | null) => {
      if (!c) return;
      c.showMessage('Hover a symbol to isolate its 1-hop neighbourhood');
      // Framing is done by hand, because neither built-in mechanism works here:
      // `config.fitOnLoad` measures before ELK resolves (and lands at ~170%), and
      // `<ElkLayout fitPadding>` does not fire on the initial run. Both are
      // instances of `docs/autofit-bounds-rfc.md`. So: fit once, after the
      // layout has landed and painted.
      window.setTimeout(() => c.fitView(60), 400);
    }, []);

    return (
      <ThemeProvider>
        <GraphCanvasApp
          data={data}
          config={config}
          onReady={onReady}
          header={{
            title: 'Code explainability — where does a node become a pixel?',
            center: <GraphControlsToolbar />,
            right: () => (
              <ToolbarItems
                orientation="horizontal"
                items={[
                  {
                    type: 'select',
                    key: 'look',
                    label: 'Look',
                    value: look,
                    options: { cards: 'Cards — what is this symbol', dots: 'Dots — what is the shape' },
                    onChange: (v) => setLook(v as 'cards' | 'dots'),
                  },
                  {
                    type: 'select',
                    key: 'direction',
                    label: 'Flow',
                    value: direction,
                    options: { RIGHT: 'Left → right', DOWN: 'Top → down' },
                    onChange: (v) => setDirection(v as ElkDirection),
                  },
                ]}
              />
            ),
          }}
          footer={{ left: <GraphStatusBar />, right: <CanvasMessageBar /> }}
        >
          {/* The bundle registers only the force layout, so the ELK id named by
              `config.activeLayout` is mounted here. `nodeSize` is a function, so
              it rides the `options` prop rather than the serialisable config —
              without it ELK lays out around points and the cards overlap. */}
          <ElkLayout
            id="elk"
            targetLayerId="graph"
            fitPadding={60}
            options={{
              direction,
              // Containers are sized by their children, so only leaves get a
              // fixed box — handing ELK a card-sized package would reserve room
              // twice.
              nodeSize: (node) =>
                node.type === 'package'
                  ? { width: 0, height: 0 }
                  : look === 'cards'
                    ? { width: CARD.width, height: CARD.height }
                    : { width: 20, height: 20 },
            }}
          />
          {/* Not in the GraphCanvasApp bundle (which registers background ·
              graph · color · theme · pan · wheel · drag-node · hover ·
              click-select · brush-select · lasso-select), so a package frame's
              +/- toggle has no listener until this is mounted — and neither
              does double-click, which `doubleClickToToggle` already enables by
              default. Behaviours never auto-enable (root rule 7). */}
          <CollapseExpandBehaviour id="collapse-expand" targetLayerId="graph" enabled />
        </GraphCanvasApp>
      </ThemeProvider>
    );
  },
};
