/**
 * **Code explainability — can I change this without breaking something?**
 *
 * **Who.** An engineer three days into a codebase they did not write, holding a
 * ticket that says "make `type` required on the node record". Or the same
 * engineer six months later, asked in review why a change is safe.
 *
 * **The question.** *Where does a node actually become a pixel — and if I change
 * its shape, what is downstream of me?*
 *
 * A file tree cannot answer that. Neither can grep: the answer is a **path**
 * through 42 symbols across 5 packages, and the useful thing about it is which
 * hops exist, not which files contain a word.
 *
 * ### The data
 *
 * `canvasDataflow` — this monorepo's own type / instance graph. Every node is a
 * real symbol with its source location on `data.file`; every edge a traced
 * relationship (`creates` · `implements` · `compiles-to` · `instantiates` · …).
 * It is **not** generated by a static analyser: it was hand-traced, which is why
 * each node carries a `purpose` line that no AST walk would produce.
 *
 * ### How the visualiser helps — step by step
 *
 * 1. **Open the whole stack.** 42 cards, coloured by side of the system —
 *    app / data / engine / render. The shape of the pipeline is one glance.
 * 2. **Read a symbol without leaving the graph.** Each card carries what kind of
 *    construct it is, who owns it, and one line on why it exists. This is the
 *    step a file tree cannot do at all.
 * 3. **Hover to isolate a neighbourhood.** Everything off the 1-hop path dims —
 *    at 42 nodes that is the only practical way to follow one thread.
 * 4. **Find the seam.** `nodeSpec` and `edgeSpec` are the *only* two crossings
 *    from graph vocabulary to canvas vocabulary. Everything above them speaks
 *    `GraphNode`; everything below speaks `BaseShapeSpec`. That is the answer to
 *    the ticket: a record change stops there.
 * 5. **Switch to dots** when the question turns from *"what is this"* to
 *    *"what is the shape"* — the same graph, the compact reading.
 * 6. **Open Settings** to re-cut the picture without editing the story: the ELK
 *    direction and spacing, the hover degree, every mounted behaviour. The panel
 *    lists exactly what this canvas registers — which is why the app bundle is
 *    off (`bundle={false}`) and the children below are the whole composition.
 *
 * ### What it makes obvious
 *
 * Three things that are true of the code and invisible in the source tree:
 *
 * - **`@invana/canvas` has no `record` node.** A shape exists only as a *spec*
 *   handed in and an *instance* the renderer holds — all persistence is
 *   graph-side. So "where is the canvas equivalent of `GraphNode`" has the
 *   answer *nowhere*, and that is by design.
 * - **`GraphStore → DataSource` is `implements`, not `extends`.** The kernel
 *   never learns what a graph is; it knows three methods.
 * - **Edges fan into four sub-choices** (anchor · router · pathStyle · marker)
 *   where nodes make one. That asymmetry explains why `NodeShapeOptions` is a
 *   discriminated union and `EdgeShapeOptions` is a flat interface.
 */

import { useCallback, useMemo, useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import {
  BackgroundLayer,
  BrushSelectBehaviour,
  ClickSelectBehaviour,
  CollapseExpandBehaviour,
  ColorByBehaviour,
  DragNodeBehaviour,
  DragPanBehaviour,
  ElkLayout,
  GraphLayer,
  HoverActivateBehaviour,
  LassoSelectBehaviour,
  ThemeBehaviour,
  WheelZoomBehaviour,
} from '@invana/canvas-react';
import {
  CanvasMessageBar,
  CanvasSettingsEditorPanel,
  CanvasThemeSync,
  GraphCanvasApp,
  GraphControlsToolbar,
  GraphStatusBar,
  ToolbarItems,
  useSidePanels,
} from '@invana/canvas-ui';
import { canvasDataflow } from '@invana/graph-datasets';
import type { CanvasConfig } from '@invana/canvas';
import type {
  GraphCanvas,
  GraphNode,
  NodeStructureRegistry,
  NodeStylingRegistry,
  NodeTypeRegistry,
} from '@invana/graph';
import { ThemeProvider } from '@invana/themes';
import { Moon, Settings, Sun } from 'lucide-react';


// ─── Presentation ────────────────────────────────────────────────────────────
//
// The dataset is data only — it describes what the symbols are, not how to draw
// them. Everything below is this story's answer to "how should they look".

/** Card box. ELK is handed the same numbers the card draws at. */
const CARD = { width: 264, height: 132 } as const;

/**
 * One structure for all 42 symbols — the cards differ by *styling*, not shape.
 *
 * The row order is the reading order: what kind of construct it is and who owns
 * it, then the name, then the one line on why it exists. `purpose` is the
 * payload; a dot with a label could never carry it.
 */
const structures: NodeStructureRegistry = {
  symbolCard: {
    name: 'symbolCard',
    kind: 'card',
    width: CARD.width,
    height: CARD.height,
    rows: [
      { slots: [{ slot: 'symbol', kind: 'tag' }, { slot: 'package', kind: 'text' }] },
      { divider: true },
      { slots: [{ slot: 'name', kind: 'text' }] },
      { slots: [{ slot: 'purpose', kind: 'text' }] },
    ],
  },
};

/**
 * One styling shape, four accents.
 *
 * The hairline border is doing real work, not decoration: a card's `cardBg` sits
 * one step off the frame it's drawn on, and at a zoom where the text stops being
 * legible that step alone isn't enough to read the card as an object. The border
 * is what keeps 42 cards countable. It goes through `strokeRole` rather than a
 * literal so it still tracks the palette in light mode.
 */
const card = (accent: number) => ({
  name: 'symbolCard',
  bgRole: 'cardBg' as const,
  strokeRole: 'stroke' as const,
  strokeWidth: 1,
  accent,
  slots: {
    symbol: { color: accent, fontSize: 10, fontWeight: 700, uppercase: true },
    package: { colorRole: 'muted' as const, fontSize: 10 },
    name: { colorRole: 'heading' as const, fontSize: 15, fontWeight: 700 },
    purpose: { colorRole: 'foreground' as const, fontSize: 11 },
    divider: { colorRole: 'divider' as const },
  },
});

/**
 * Four stylings, grouped by **side of the stack** rather than by the twelve
 * `type` layers — the accent works as a legend, and twelve accents would be
 * noise. Roles carry the theme; only `accent` is a literal, because the palette
 * exposes one accent role and this card wants four.
 */
const stylings: NodeStylingRegistry = {
  appCard: card(0x8b5cf6), // React + facade — where a consumer starts
  dataCard: card(0x10b981), // records, styles, stores — the data lanes
  engineCard: card(0xf59e0b), // engine, layer, behaviour, interface
  renderCard: card(0xf43f5e), // spec, instance, renderer — canvas-side
};

/** Bindings are dotted paths into the payload — one path per slot, verbatim. */
const bind = (styling: string) => ({
  structure: 'symbolCard',
  styling,
  bindings: {
    symbol: 'data.symbol',
    package: 'data.package',
    name: 'data.name',
    purpose: 'data.purpose',
  },
});

/** Every stack layer binds to the same structure, styled by its side. */
const nodeTypes: NodeTypeRegistry = {
  react: bind('appCard'),
  facade: bind('appCard'),
  engine: bind('engineCard'),
  layer: bind('engineCard'),
  behaviour: bind('engineCard'),
  interface: bind('engineCard'),
  store: bind('dataCard'),
  record: bind('dataCard'),
  style: bind('dataCard'),
  spec: bind('renderCard'),
  instance: bind('renderCard'),
  renderer: bind('renderCard'),
};

/**
 * Cards — the default. `purpose` is the payload and a labelled dot cannot carry
 * a sentence.
 *
 * Colour-by-type is **off**: the card styling owns the fill, and a `bgFill`
 * resolver would fight it. Type is still doing the work — it *selects* which
 * styling a node gets.
 *
 * `fitOnLoad` is off deliberately: it measures before a one-shot layout resolves
 * and lands at ~170% (`docs/autofit-bounds-rfc.md`).
 */
const CARD_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    // The app bundle is off (`bundle={false}` below — it would register a
    // d3-force layout this story has no use for), so every setting the bundle
    // used to supply is spelled out here, keyed by the id each JSX child
    // registers under.
    background: { type: 'pattern', patternType: 'grid', alpha: 0.5 },
    graph: {
      nodeStructureTemplates: structures,
      nodeStylingTemplates: stylings,
      nodeTypes,
      node: {
        style: {
          // The dataset states the hierarchy (`parentId` → package); whether it
          // *renders* as a frame is presentation, so the resolver lives here.
          // `style.group` is what makes a node a container — see
          // `GraphLayer.isGroupNode`.
          //
          // `autoFit` is REQUIRED, not decoration: it defaults to `false`, and
          // without it the frame ignores its children and draws at its declared
          // size. A package node carries no `style.shape`, so that size is the
          // engine fallback (`{ kind: 'circle', radius: 10 }`) — a 10px dot that
          // reads as "collapsed" no matter how many symbols it holds.
          group: (node: GraphNode) =>
            node.type === 'package' ? { autoFit: true, padding: 28, headerHeight: 26 } : undefined,
          // A package declares no shape of its own, so without this it falls to
          // the engine default (`circle radius:10`) and autoFit grows that into
          // a vast enclosing circle. A frame around a dozen cards wants a rect.
          //
          // The declared size does double duty and both halves matter: expanded
          // it is the *floor* autoFit raises to the children bbox + padding, and
          // **collapsed it is the size the frame keeps** — autoFit is skipped and
          // a rect has no `collapsedOf` minimal form. Declaring `0 × 0` framed
          // correctly but closed to a 0×0 rect: an invisible node you can't
          // double-click to re-open. So: card-width, one header tall.
          shape: (node: GraphNode) =>
            node.type === 'package'
              ? { kind: 'rect' as const, width: CARD.width, height: 52, cornerRadius: 14 }
              : undefined,
          // **A group node is just a node, so it takes ordinary node styling.**
          // There is no group-specific fill channel and none is needed — `fill`
          // and `stroke` come off the resolved style with no special-casing for
          // frames (`GraphLayer.ts:1526`). Left unset (the default), a package
          // has no fill at all and the frame, its cards and the backdrop read as
          // one flat slab.
          //
          // Three surfaces, and the frame has to sit *between* the backdrop and
          // the card so the card still reads as the raised thing. The card's own
          // colours go through roles (`bgRole: 'cardBg'`, `strokeRole`), so they
          // follow the theme — but a raw `NodeStyle` colour is a plain number
          // with no role channel, so a literal picked for dark mode would be
          // wrong the moment the header's theme toggle flips to light.
          //
          // The way out is a **neutral tinted with alpha rather than a chosen
          // colour**: mid-slate at 14% composites *against whatever backdrop is
          // behind it*. Over the dark backdrop it lands near 0x1b2436 — a step
          // up from the background, a step below `cardBg`. Over the light one it
          // lands near 0xe9ecf0 — a step *down* from the background, with the
          // near-white card still the raised surface. The ordering that makes a
          // card read as raised survives either way, from one pair of values.
          //
          // The alpha goes on the **fill layer**, not on `bgAlpha`: `bgAlpha` is
          // the whole shape's opacity (`GraphLayer.ts:1518` — it becomes
          // `spec.alpha`), so it multiplies the border too. A 0.5 border under
          // `bgAlpha: 0.14` paints at 0.07 — which is why these frames looked
          // borderless. `{ kind: 'solid', … alpha }` tints only the fill and
          // leaves the outline at full strength.
          bgFill: (node: GraphNode) =>
            node.type === 'package' ? { kind: 'solid' as const, color: 0x64748b, alpha: 0.14 } : undefined,
          bgStrokeColor: (node: GraphNode) => (node.type === 'package' ? 0x94a3b8 : undefined),
          bgStrokeAlpha: (node: GraphNode) => (node.type === 'package' ? 0.75 : undefined),
          bgStrokeWidth: (node: GraphNode) => (node.type === 'package' ? 1.5 : undefined),
          labelText: (node: GraphNode) => (node.type === 'package' ? node.id : undefined),
        },
      },
      edge: {
        style: {
          strokeColor: 0x94a3b8,
          // Legible at the zoom this graph actually gets read at. 42 cards fit
          // at ~26%, where a 1.2px line at 40% alpha is a sub-pixel smudge —
          // the edges were marginal even over open backdrop, before the group
          // frames were painting over them at all.
          strokeWidth: 1.6,
          strokeAlpha: 0.7,
          arrowTargetShape: 'triangle',
          arrowTargetSize: 5,
        },
      },
    },
  },
  layouts: {
    // LEFT-TO-RIGHT: the stack reads app → data → engine → render, which is a
    // sentence, and sentences read across.
    elk: {
      algorithm: 'layered',
      direction: 'RIGHT',
      // These apply at both levels — between the package frames *and* between
      // the cards inside them — so they're a compromise, not a per-level tune.
      //
      // They were briefly much larger (96 / 190) to force the frames apart, back
      // when a container's members were pinned at ELK's default 20px spacing no
      // matter what was configured (fixed in `ElkLayout`'s `nestedLayoutOptions`
      // — containers declare their own `layoutOptions`, so they used to opt out
      // of every spacing key set on the root). With the inner spacing honoured,
      // those numbers inflated the graph to ~18% zoom-to-fit; these are the
      // values that read well now that one setting actually reaches both levels.
      nodeSpacing: 48,
      layerSpacing: 140,
      edgeNodeSpacing: 24,
      edgeSpacing: 14,
      padding: 40,
    },
  },
  behaviours: {
    // Colour-by-type is off: the card styling owns the fill, and a `bgFill`
    // resolver would fight it.
    color: { enabled: false },
    hover: { enabled: true, state: 'highlighted', inactiveState: 'dimmed', degree: 1, direction: 'both' },
    pan: { enabled: true },
    wheel: { enabled: true },
    'drag-node': { enabled: true },
    'click-select': { enabled: true, multiple: true },
    // Registered disarmed — the toolbar's select-mode picker arms one at a time.
    'brush-select': { enabled: false },
    'lasso-select': { enabled: false },
    // A package frame's +/- toggle and double-click-to-collapse.
    'collapse-expand': { enabled: true },
    // The sole theme publisher; `<CanvasThemeSync>` pins its mode + family to
    // the host `<ThemeProvider>`, so the header toggle repaints the canvas.
    theme: { enabled: true, mode: 'system', active: 'default', accent: 'css-var' },
  },
};

/**
 * Dots — the compact reading. Same graph, different question: cards answer
 * *"what is this symbol"*, dots answer *"what is the shape of the pipeline"*.
 * Colour-by-type is on here because nothing competes for the fill.
 */
const DOT_CONFIG: CanvasConfig = {
  activeLayout: 'elk',
  fitOnLoad: false,
  layers: {
    background: { type: 'pattern', patternType: 'grid', alpha: 0.5 },
    graph: {
      node: {
        style: {
          // `autoFit` + the rect frame for the same reasons as CARD_CONFIG —
          // see the notes there. Here the dot shape is set for every node, so
          // the package has to override it rather than fill a gap.
          group: (node: GraphNode) =>
            node.type === 'package' ? { autoFit: true, padding: 20, headerHeight: 22 } : undefined,
          shape: (node: GraphNode) =>
            node.type === 'package'
              ? { kind: 'rect' as const, width: 168, height: 40, cornerRadius: 12 }
              : { kind: 'circle' as const, radius: 8 },
          // The same theme-agnostic tinted neutral as CARD_CONFIG, and the same
          // reason the tint lives on the fill layer rather than `bgAlpha` (which
          // would fade the border with it) — see the notes there. The frame
          // takes the muted border and the dot keeps a brighter rim, or a 168×40
          // ringed pill would read as the loudest thing on screen. The dot's rim
          // is a role-free literal too, so it gets the same treatment: slate
          // reads against both backdrops where white disappears into the light
          // one.
          bgFill: (node: GraphNode) =>
            node.type === 'package' ? { kind: 'solid' as const, color: 0x64748b, alpha: 0.14 } : undefined,
          bgStrokeColor: 0x94a3b8,
          bgStrokeAlpha: (node: GraphNode) => (node.type === 'package' ? 0.75 : 0.9),
          bgStrokeWidth: 1.5,
          labelFontSize: 10,
          labelPlacement: 'bottom',
          labelOffsetY: 4,
        },
      },
      edge: {
        style: { strokeColor: 0x94a3b8, strokeWidth: 1.6, strokeAlpha: 0.7, arrowTargetShape: 'none' },
      },
    },
  },
  layouts: {
    elk: { algorithm: 'layered', direction: 'RIGHT', nodeSpacing: 18, layerSpacing: 90, padding: 30 },
  },
  // Same hand-rolled bundle as CARD_CONFIG (see the note there) — except
  // colour-by-type, which is on here because nothing competes for the fill.
  behaviours: {
    color: { enabled: true },
    hover: { enabled: true, state: 'highlighted', inactiveState: 'dimmed', degree: 1, direction: 'both' },
    pan: { enabled: true },
    wheel: { enabled: true },
    'drag-node': { enabled: true },
    'click-select': { enabled: true, multiple: true },
    'brush-select': { enabled: false },
    'lasso-select': { enabled: false },
    'collapse-expand': { enabled: true },
    theme: { enabled: true, mode: 'system', active: 'default', accent: 'css-var' },
  },
};

const meta: Meta = { title: 'usecases/by-casestudies/code-explainability/CodeExplainability' };
export default meta;
type Story = StoryObj;

export const CodeExplainabilityStory: Story = {
  name: 'CodeExplainability',
  render: function CodeExplainabilityRender() {
    /** Cards carry the prose; dots carry the topology. Same graph either way. */
    const [look, setLook] = useState<'cards' | 'dots'>('cards');

    // Settings docks `<CanvasSettingsEditorPanel>` into the right region — the
    // ELK direction / spacing and every mounted behaviour, editable live. That
    // panel is why the header carries no layout controls of its own.
    const dock = useSidePanels(
      [
        {
          id: 'settings',
          icon: Settings,
          label: 'Settings',
          render: (c) => (
            <CanvasSettingsEditorPanel canvas={c} className="border-0 bg-transparent shadow-none" />
          ),
        },
      ],
      { section: { defaultSize: '380px', maxSize: '520px' } },
    );

    // Memoised so a toolbar change never hands GraphCanvasApp a new `data`
    // identity and reloads the engine.
    const data = useMemo(() => canvasDataflow, []);
    const config = useMemo(
      () => (look === 'cards' ? CARD_CONFIG : DOT_CONFIG),
      [look],
    );

    const onReady = useCallback((c: GraphCanvas | null) => {
      if (!c) return;
      c.showMessage('Hover a symbol to isolate its 1-hop neighbourhood');
      // No fit here. `config.fitOnLoad` is off (it measures before a one-shot
      // layout resolves — `docs/autofit-bounds-rfc.md`), and a hand-rolled
      // `setTimeout(fitView, 400)` is the same bug on a timer: ELK's solve time
      // moves with the look, so the timer fires mid-solve and frames a near-empty
      // bbox — ~770% on the dot look. `<ElkLayout fitPadding={60}>` fits off the
      // layout's own `end` event instead, which is the only signal that can't be
      // early.
    }, []);

    return (
      <ThemeProvider>
        <GraphCanvasApp
          data={data}
          config={config}
          onReady={onReady}
          // `bundle={false}` — the batteries-included bundle registers a
          // d3-force layout, and this graph is laid out by ELK alone. Turning it
          // off makes the children below the *whole* canvas, which is also what
          // keeps the settings panel honest: it lists exactly what's mounted, so
          // a layout nothing points at never shows up as an editable surface.
          bundle={false}
          // The switch below is not a config *tweak*: cards and dots differ in
          // which node templates exist at all. `config` is applied with
          // `canvas.update()`, which deep-merges (`Canvas.ts:761`) — and
          // `GraphLayer.setOptions` merges `nodeTypes` key-by-key
          // (`GraphLayer.ts:874`), so a merge can never *remove* the card
          // bindings. Without a remount the graph stays cards forever (the type
          // binding is applied above the layer template, `GraphLayer.ts:967`).
          // `instanceKey` exists for exactly this: re-init and apply the new
          // config from scratch.
          instanceKey={look}
          header={{
            title: 'Code explainability — where does a node become a pixel?',
            // No layout picker: its default factory constructs a `D3ForceLayout`
            // (`GraphControlsToolbar.tsx:56`), which would put d3-force back in
            // through the front door. ELK's own options live in Settings.
            center: <GraphControlsToolbar sections={{ layout: false }} />,
            right: (ctx) => (
              <ToolbarItems
                orientation="horizontal"
                items={[
                  {
                    type: 'select',
                    key: 'look',
                    label: 'Look',
                    value: look,
                    options: { cards: 'Cards — what is this symbol', dots: 'Dots — what is the shape' },
                    onChange: (v) => setLook(v as 'cards' | 'dots'),
                  },
                  ...dock.items,
                  {
                    type: 'toggle',
                    key: 'theme',
                    icon: Sun,
                    activeIcon: Moon,
                    label: 'Switch to dark theme',
                    activeLabel: 'Switch to light theme',
                    active: ctx.themeKind === 'dark',
                    onToggle: ctx.toggleTheme,
                  },
                ]}
              />
            ),
          }}
          footer={{ left: <GraphStatusBar />, right: <CanvasMessageBar /> }}
          right={dock.region}
        >
          {/* With the bundle off, these children *are* the canvas — the same set
              `GraphCanvasApp` would have mounted, minus the force layout, plus
              ELK and collapse/expand. Every option comes from `config`, keyed by
              the id each one registers under. */}
          <BackgroundLayer id="background" />
          <GraphLayer id="graph" data={data} />
          <ColorByBehaviour id="color" targetLayerId="graph" />
          {/* The sole theme publisher + the sync that drives its mode/family off
              the host `<ThemeProvider>` — that pair is what makes the header's
              sun/moon toggle repaint the canvas and not just the chrome. */}
          <ThemeBehaviour id="theme" />
          <CanvasThemeSync />
          <DragPanBehaviour id="pan" />
          <WheelZoomBehaviour id="wheel" />
          <DragNodeBehaviour id="drag-node" targetLayerId="graph" />
          <HoverActivateBehaviour id="hover" targetLayerId="graph" />
          <ClickSelectBehaviour id="click-select" targetLayerId="graph" />
          <BrushSelectBehaviour id="brush-select" targetLayerId="graph" />
          <LassoSelectBehaviour id="lasso-select" targetLayerId="graph" />
          {/* The one layout, named by `config.activeLayout`. `nodeSize` is a
              function, so it rides the `options` prop rather than the
              serialisable config — without it ELK lays out around points and the
              cards overlap. `direction` is deliberately *not* here: it lives in
              `config.layouts.elk`, so the Settings panel can drive it (wrapper
              options are init-only; config wins by id). */}
          <ElkLayout
            id="elk"
            targetLayerId="graph"
            fitPadding={60}
            options={{
              // Containers are sized by their children, so only leaves get a
              // fixed box — handing ELK a card-sized package would reserve room
              // twice.
              nodeSize: (node) =>
                node.type === 'package'
                  ? { width: 0, height: 0 }
                  : look === 'cards'
                    ? { width: CARD.width, height: CARD.height }
                    : { width: 20, height: 20 },
            }}
          />
          {/* A package frame's +/- toggle has no listener until this is mounted —
              and neither does double-click, which `doubleClickToToggle` already
              enables by default. Behaviours never auto-enable (root rule 7). */}
          <CollapseExpandBehaviour id="collapse-expand" targetLayerId="graph" enabled />
        </GraphCanvasApp>
      </ThemeProvider>
    );
  },
};
