import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Cable,
  ClipboardPaste,
  Copy,
  CornerDownRight,
  Crosshair,
  Download,
  Eraser,
  Expand,
  Grid3x3,
  Hand,
  Info,
  Keyboard,
  Lasso,
  Layers,
  LocateFixed,
  Lock,
  LockOpen,
  Maximize,
  Minus,
  Mouse,
  Move,
  Moon,
  MousePointer2,
  Play,
  Plus,
  Redo2,
  RefreshCw,
  Scissors,
  Search,
  Settings,
  Shrink,
  Spline,
  Square,
  SquareDashedMousePointer,
  Sun,
  Trash2,
  Undo2,
  Waypoints,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

import type { ToolbarIcon } from '../components';

/**
 * The default **icon registry** for control panels: the names a serialised
 * `ControlItemSpec.icon` may use, mapped to lucide glyphs. Kebab-case, named for
 * the glyph (not the command), so one icon can serve several commands. Extend or
 * override per app via `<ControlPanels icons={…}>`.
 */
export const DEFAULT_CONTROL_ICONS: Readonly<Record<string, ToolbarIcon>> = {
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  maximize: Maximize,
  expand: Expand,
  shrink: Shrink,
  crosshair: Crosshair,
  lock: Lock,
  'lock-open': LockOpen,
  play: Play,
  stop: Square,
  refresh: RefreshCw,
  undo: Undo2,
  redo: Redo2,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  minus: Minus,
  x: X,
  search: Search,
  settings: Settings,
  layers: Layers,
  info: Info,
  download: Download,
  pointer: MousePointer2,
  spline: Spline,
  hand: Hand,
  // camera / input
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  locate: LocateFixed,
  move: Move,
  mouse: Mouse,
  keyboard: Keyboard,
  // edit / history
  scissors: Scissors,
  copy: Copy,
  'clipboard-paste': ClipboardPaste,
  eraser: Eraser,
  trash: Trash2,
  // selection modes
  'select-box': SquareDashedMousePointer,
  lasso: Lasso,
  grid: Grid3x3,
  // edge routing (`graph.edgeType` options name these `edge-<pathType>`)
  'edge-straight': Minus,
  'edge-orth': CornerDownRight,
  'edge-bezier': Spline,
  'edge-rounded': Waypoints,
  'edge-smooth': Cable,
};
