// @invana/graph — public API surface
//
// GraphLayer + MiniMapLayer + behaviours per `architecture-proposal.md` §5.
// GraphStore is the data layer composing `@invana/canvas` ColumnStore.

export {
  GraphStore,
  type EdgeDirection,
  type GraphEdge,
  type GraphElementKind,
  type GraphNode,
  type GraphStoreEventMap,
  type GraphStoreOptions,
  type Vec2,
} from './store';

export {
  DEFAULT_EDGE_STATES,
  DEFAULT_NODE_STATES,
  GraphLayer,
  isBuiltInNodeShape,
  MiniMapLayer,
  resolveField,
  type CanonicalStateName,
  type MiniMapLayerOptions,
  type MiniMapPosition,
  type MiniMapColor,
  type MiniMapMode,
  type MiniMapKind,
  type EdgeAnchor,
  type EdgePathType,
  type GraphData,
  type GraphLayerEvents,
  type GraphLayerOptions,
  type Resolvable,
  // v3 G6-aligned shape
  type ArcShapeOption,
  type ArrowShape,
  type BadgeEffects,
  type BadgeOrigin,
  type BadgePlacement,
  type BuiltInNodeShapeOptions,
  type CircleShapeOption,
  type CompositeShapeOption,
  type CustomShapeOption,
  type EdgeBadge,
  type EdgeBadgePlacement,
  type EdgeData,
  type EdgeInput,
  type EdgeOption,
  type EdgeShapeOptions,
  type EdgeStyle,
  type GraphDataOptions,
  type GroupOptions,
  type NodeBadge,
  type NodeData,
  type NodeDecorationSpec,
  type EdgeDecorationSpec,
  type DecorationSpecCommon,
  type NodeEffects,
  type NodeIcon,
  type NodeImage,
  type NodeInput,
  type NodeOption,
  type NodeShapeOptions,
  type NodeStyle,
  type PolygonShapeOption,
  type RectShapeOption,
  type RegularPolygonShapeOption,
  type ResolvableEdgeStyle,
  type ResolvableId,
  type ResolvableNodeStyle,
  type StarShapeOption,
} from './layer';

export { GraphCanvas } from './canvas';

export {
  OneShotPositionLayout,
  type OneShotLayoutOptions,
  type LayoutPositions,
} from './layout/OneShotPositionLayout';

export {
  GraphHistory,
  type GraphHistoryEventMap,
  type GraphHistoryOptions,
  type HistoryEntry,
  type HistoryOp,
  type HistoryRecorder,
} from './history';

export {
  GraphClipboard,
  type GraphClipboardEventMap,
  type GraphClipboardOptions,
  type PasteResult,
} from './clipboard';

export {
  HoverActivateBehaviour,
  type HoverActivateBehaviourOptions,
  type HoverableElement,
  type HoverableElementType,
  type HoverDirection,
  ClickSelectBehaviour,
  type ClickSelectBehaviourOptions,
  type ClickSelectEventMap,
  type SelectableElement,
  type SelectableElementType,
  type SelectDirection,
  type SelectModifierKey,
  type SelectionSnapshot,
  ClickInspectBehaviour,
  type ClickInspectBehaviourOptions,
  type ClickInspectEventMap,
  type InspectTarget,
  ClickViewBehaviour,
  type ClickViewBehaviourOptions,
  type ClickViewEventMap,
  type ViewTarget,
  HoverElementPreviewBehaviour,
  resolvePreviewCard,
  type HoverElementPreviewBehaviourOptions,
  type HoverElementPreviewCardSpec,
  type HoverElementPreviewCardsByType,
  type HoverElementPreviewEventMap,
  type PreviewCardRow,
  type PreviewFieldPath,
  type PreviewImageSpec,
  type PreviewPlacement,
  type PreviewRowFormat,
  type PreviewRowSpec,
  type PreviewSnapshot,
  type PreviewSubtitleSpec,
  type PreviewTextSpec,
  type ResolvedPreviewCard,
  ColorByLabelBehaviour,
  DEFAULT_LABEL_PALETTE,
  type ColorByLabelBehaviourOptions,
  type ColorLabelAccessor,
  BrushSelectBehaviour,
  type BrushSelectBehaviourOptions,
  type BrushSelectElementType,
  type BrushSelectStyle,
  type BrushModifierKey,
  LassoSelectBehaviour,
  type LassoSelectBehaviourOptions,
  type LassoSelectElementType,
  type LassoSelectStyle,
  type LassoModifierKey,
  DragNodeBehaviour,
  type DragNodeBehaviourOptions,
  ContextMenuBehaviour,
  type ContextMenuBehaviourOptions,
  type ContextMenuEvent,
  type ContextMenuTargetType,
  CreateNodeBehaviour,
  type CreateNodeBehaviourOptions,
  DrawEdgeBehaviour,
  type DrawEdgeBehaviourOptions,
  EraseBehaviour,
  type EraseBehaviourOptions,
  type EraseTargetKind,
  type ErasedElement,
  CollapseExpandBehaviour,
  GROUP_TOGGLE_SLOT,
  type CollapseExpandBehaviourOptions,
  NodeResizeBehaviour,
  type NodeResizeBehaviourOptions,
  LabelCollisionBehaviour,
  type LabelCollisionBehaviourOptions,
  type LabelCollisionStrategy,
  type LabelPriorityResolver,
  TextResolutionLODBehaviour,
  type TextResolutionLODBehaviourOptions,
  NodeScaleLODBehaviour,
  type NodeScaleLODBehaviourOptions,
  type NodeScaleLODConfig,
  EdgeScaleLODBehaviour,
  type EdgeScaleLODBehaviourOptions,
  type EdgeScaleLODConfig,
  ParallelEdgeBehaviour,
  centeredRanksPolicy,
  type ParallelEdgeBasis,
  type ParallelEdgeBehaviourOptions,
  type ParallelEdgeDistribute,
  type ParallelEdgeDistributeContext,
  type ParallelEdgeGroup,
  type ParallelEdgePatch,
  NodeCentralityBehaviour,
  type NodeCentralityBehaviourOptions,
  type NodeCentralityScale,
  type ContentLODBehaviourOptions,
  type ZoomBand,
  TextLODBehaviour,
  type TextLODBehaviourOptions,
  IconLODBehaviour,
  type IconLODBehaviourOptions,
  ImageLODBehaviour,
  type ImageLODBehaviourOptions,
  ThemeBehaviour,
  type ThemeBehaviourOptions,
} from './behaviours';

// ─── Theme (named palettes + roles) ────────────────────────────────────────
export {
  type ColorRole,
  type Theme,
  type ThemePalette,
  type ThemeRegistry,
  type ThemeMode,
  type ThemeKind,
  BUILT_IN_THEMES,
  DEFAULT_THEME,
  FOREST_THEME,
  OCEAN_THEME,
  GOLD_THEME,
  ROSE_THEME,
  MINIMAL_THEME,
  cssColorToNumber,
  resolveAccentVar,
  themeFamily,
} from './theme';

// ─── Node structure / styling templates ────────────────────────────────────
export {
  type NodeStructureTemplate,
  type SimpleStructure,
  type CardStructure,
  type CardRow,
  type CardSlot,
  type FreeformStructure,
  type CardElement,
  type CardElementCommon,
  type NodeStylingTemplate,
  type SlotStyling,
  type LabelStyling,
  type NodeTypeBinding,
  type NodeStructureRegistry,
  type NodeStylingRegistry,
  type NodeTypeRegistry,
  resolvePath,
  resolveText,
  compileSimple,
  compileCard,
  compileFreeform,
  BUILT_IN_STRUCTURES,
  BUILT_IN_STYLINGS,
} from './template';

// ─── Built-in composite card node types ─────────────────────────────────────
export {
  CompositeCard,
  type CardFrame,
  SchemaTableCard,
  schemaTableCard,
  SCHEMA_TABLE_CARD_DEFAULTS,
  type SchemaTableCardSpec,
  type SchemaTableCardOptions,
  UserCard,
  userCard,
  USER_CARD_DEFAULTS,
  type UserCardSpec,
  StatCard,
  statCard,
  STAT_CARD_DEFAULTS,
  type StatCardSpec,
  TaskCard,
  taskCard,
  TASK_CARD_DEFAULTS,
  type TaskCardSpec,
  iconifyUrl,
  CARD_BG,
  CARD_STROKE,
  type SchemaField,
  type SchemaTableData,
  type UserCardData,
  type StatCardData,
  type TaskTag,
  type TaskCardData,
} from './cards';

