// @invana/graph — public API surface
//
// GraphLayer + MiniMapLayer + behaviours per `architecture-proposal.md` §5.
// GraphStore is the data layer composing `@invana/canvas` ColumnStore.

export {
  GraphStore,
  type EdgeDirection,
  type GraphEdge,
  type GraphNode,
  type GraphStoreEventMap,
  type GraphStoreOptions,
  type Vec2,
} from './store';

export {
  DEFAULT_EDGE_STATES,
  DEFAULT_NODE_STATES,
  GraphLayer,
  isBuiltInNodeShape,
  MiniMapLayer,
  resolveField,
  type CanonicalStateName,
  type MiniMapLayerOptions,
  type MiniMapPosition,
  type MiniMapColor,
  type MiniMapMode,
  type MiniMapKind,
  type EdgeAnchor,
  type EdgePathType,
  type GraphData,
  type GraphLayerEvents,
  type GraphLayerOptions,
  type Resolvable,
  // v3 G6-aligned shape
  type ArcShapeOption,
  type ArrowShape,
  type BadgeEffects,
  type BadgeOrigin,
  type BadgePlacement,
  type BuiltInNodeShapeOptions,
  type CircleShapeOption,
  type CustomShapeOption,
  type EdgeBadge,
  type EdgeBadgePlacement,
  type EdgeData,
  type EdgeInput,
  type EdgeOption,
  type EdgeShapeOptions,
  type EdgeStyle,
  type GraphDataOptions,
  type GroupOptions,
  type NodeBadge,
  type NodeData,
  type NodeDecorationSpec,
  type EdgeDecorationSpec,
  type DecorationSpecCommon,
  type NodeEffects,
  type NodeIcon,
  type NodeImage,
  type NodeInput,
  type NodeOption,
  type NodeShapeOptions,
  type NodeStyle,
  type PolygonShapeOption,
  type RectShapeOption,
  type RegularPolygonShapeOption,
  type ResolvableEdgeStyle,
  type ResolvableId,
  type ResolvableNodeStyle,
  type StarShapeOption,
} from './layer';

export { GraphCanvas } from './canvas';

export {
  OneShotPositionLayout,
  type OneShotLayoutOptions,
  type LayoutPositions,
} from './layout/OneShotPositionLayout';

export {
  GraphHistory,
  type GraphHistoryEventMap,
  type GraphHistoryOptions,
  type HistoryEntry,
  type HistoryOp,
  type HistoryRecorder,
} from './history';

export {
  GraphClipboard,
  type GraphClipboardEventMap,
  type GraphClipboardOptions,
  type PasteResult,
} from './clipboard';

export {
  HoverActivateBehaviour,
  type HoverActivateBehaviourOptions,
  type HoverableElement,
  type HoverableElementType,
  type HoverDirection,
  ClickSelectBehaviour,
  type ClickSelectBehaviourOptions,
  type ClickSelectEventMap,
  type SelectableElement,
  type SelectableElementType,
  type SelectDirection,
  type SelectModifierKey,
  type SelectionSnapshot,
  ClickInspectBehaviour,
  type ClickInspectBehaviourOptions,
  type ClickInspectEventMap,
  type InspectTarget,
  ClickViewBehaviour,
  type ClickViewBehaviourOptions,
  type ClickViewEventMap,
  type ViewTarget,
  ColorByLabelBehaviour,
  DEFAULT_LABEL_PALETTE,
  type ColorByLabelBehaviourOptions,
  type ColorLabelAccessor,
  BrushSelectBehaviour,
  type BrushSelectBehaviourOptions,
  type BrushSelectElementType,
  type BrushSelectStyle,
  type BrushModifierKey,
  LassoSelectBehaviour,
  type LassoSelectBehaviourOptions,
  type LassoSelectElementType,
  type LassoSelectStyle,
  type LassoModifierKey,
  DragNodeBehaviour,
  type DragNodeBehaviourOptions,
  ContextMenuBehaviour,
  type ContextMenuBehaviourOptions,
  type ContextMenuEvent,
  type ContextMenuTargetType,
  CreateNodeBehaviour,
  type CreateNodeBehaviourOptions,
  DrawEdgeBehaviour,
  type DrawEdgeBehaviourOptions,
  EraseBehaviour,
  type EraseBehaviourOptions,
  type EraseTargetKind,
  type ErasedElement,
  CollapseExpandBehaviour,
  GROUP_TOGGLE_SLOT,
  type CollapseExpandBehaviourOptions,
  NodeResizeBehaviour,
  type NodeResizeBehaviourOptions,
  LabelCollisionBehaviour,
  type LabelCollisionBehaviourOptions,
  type LabelCollisionStrategy,
  type LabelPriorityResolver,
  LabelResolutionLODBehaviour,
  type LabelResolutionLODBehaviourOptions,
  NodeSizeLODBehaviour,
  type NodeSizeLODBehaviourOptions,
  type NodeSizeLODConfig,
  EdgeSizeLODBehaviour,
  type EdgeSizeLODBehaviourOptions,
  type EdgeSizeLODConfig,
  ParallelEdgeBehaviour,
  centeredRanksPolicy,
  type ParallelEdgeBasis,
  type ParallelEdgeBehaviourOptions,
  type ParallelEdgeDistribute,
  type ParallelEdgeDistributeContext,
  type ParallelEdgeGroup,
  type ParallelEdgePatch,
  DegreeSizeBehaviour,
  type DegreeSizeBehaviourOptions,
  type DegreeSizeScale,
  ResponsiveThemeBehaviour,
  type ResponsiveThemeBehaviourOptions,
  type ThemeKind,
  type ThemeMode,
  type ThemeVariants,
} from './behaviours';

