// @invana/graph — public API surface
//
// GraphLayer + MiniMapLayer + behaviours per `architecture-proposal.md` §5.
// GraphStore is the data layer composing `@invana/canvas` ColumnStore.

export {
  GraphStore,
  type EdgeDirection,
  type GraphEdge,
  type GraphNode,
  type GraphStoreEventMap,
  type GraphStoreOptions,
  type Vec2,
} from './store';

export {
  DEFAULT_EDGE_STATES,
  DEFAULT_NODE_STATES,
  GraphLayer,
  isBuiltInNodeShape,
  MiniMapLayer,
  resolveField,
  type CanonicalStateName,
  type MiniMapLayerOptions,
  type MiniMapPosition,
  type EdgeAnchor,
  type EdgePathType,
  type GraphData,
  type GraphLayerEvents,
  type GraphLayerOptions,
  type Resolvable,
  // v3 G6-aligned shape
  type ArcShapeOption,
  type ArrowShape,
  type BadgePlacement,
  type BuiltInNodeShapeOptions,
  type CircleShapeOption,
  type CustomShapeOption,
  type EdgeData,
  type EdgeInput,
  type EdgeOption,
  type EdgeShapeOptions,
  type EdgeStyle,
  type GraphDataOptions,
  type GroupOptions,
  type NodeBadge,
  type NodeData,
  type NodeDecorationSpec,
  type EdgeDecorationSpec,
  type DecorationSpecCommon,
  type NodeEffects,
  type NodeIcon,
  type NodeImage,
  type NodeInput,
  type NodeOption,
  type NodeShapeOptions,
  type NodeStyle,
  type PolygonShapeOption,
  type RectShapeOption,
  type RegularPolygonShapeOption,
  type ResolvableEdgeStyle,
  type ResolvableId,
  type ResolvableNodeStyle,
  type StarShapeOption,
} from './layer';

export {
  HoverActivateBehaviour,
  type HoverActivateBehaviourOptions,
  type HoverableElement,
  type HoverableElementType,
  type HoverDirection,
  ClickSelectBehaviour,
  type ClickSelectBehaviourOptions,
  type SelectableElement,
  type SelectableElementType,
  type SelectDirection,
  type SelectModifierKey,
  type SelectionSnapshot,
  BrushSelectBehaviour,
  type BrushSelectBehaviourOptions,
  type BrushSelectElementType,
  type BrushSelectStyle,
  type BrushModifierKey,
  LassoSelectBehaviour,
  type LassoSelectBehaviourOptions,
  type LassoSelectElementType,
  type LassoSelectStyle,
  type LassoModifierKey,
  DragNodeBehaviour,
  type DragNodeBehaviourOptions,
  CollapseExpandBehaviour,
  GROUP_TOGGLE_SLOT,
  type CollapseExpandBehaviourOptions,
  NodeResizeBehaviour,
  type NodeResizeBehaviourOptions,
  LabelCollisionBehaviour,
  type LabelCollisionBehaviourOptions,
  type LabelCollisionStrategy,
  type LabelPriorityResolver,
  LabelResolutionLODBehaviour,
  type LabelResolutionLODBehaviourOptions,
  NodeSizeLODBehaviour,
  type NodeSizeLODBehaviourOptions,
  type NodeSizeLODConfig,
  EdgeSizeLODBehaviour,
  type EdgeSizeLODBehaviourOptions,
  type EdgeSizeLODConfig,
  ParallelEdgeBehaviour,
  centeredRanksPolicy,
  type ParallelEdgeBasis,
  type ParallelEdgeBehaviourOptions,
  type ParallelEdgeDistribute,
  type ParallelEdgeDistributeContext,
  type ParallelEdgeGroup,
  type ParallelEdgePatch,
} from './behaviours';

